routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); });

//Route::get('/', function () { return view('custom'); });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/mypage','pageController@index');
Route::get('/view-profile', 'HomeController@viewProfile');
Route::get('{id}/edit', 'HomeController@edit');
Route::post('/update-profile', 'HomeController@updateProfile');

Route::get('/pages/pushstack', function() { return view('pages.pushstack'); });

//Custom Password reset routes
/*Route::get('/password/confirm' , 'CustomAuth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('/password/confirm' , 'CustomAuth\ConfirmPasswordController@confirm');
Route::post('/password/email' , 'CustomAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('custom-auth/password/reset' , 'CustomAuth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('custom-auth/password/reset' , 'CustomAuth\ResetPasswordController@reset')->name('password.update');
Route::get('/password/reset/{token?}' , 'CustomAuth\ResetPasswordController@showResetForm')->name('password.reset');*/


Route::get('/custom-auth/login' , 'CustomAuth\LoginController@index')->name('custom-auth/login');
Route::post('/custom-auth/login' , 'CustomAuth\LoginController@login');
Route::get('/custom-auth/logout' , 'CustomAuth\LoginController@logout');
Route::get('/custom-auth/forgot-password' , 'CustomAuth\ForgotPasswordController@index');

Route::get('/CustomHome' , 'CustomHomeController@index');
Route::get('/edit-profile/{id}' , 'CustomAuth\EditProfileController@index');
Route::post('/edit-profile/{id}' , 'CustomAuth\EditProfileController@updateProfile');

Route::get('/custom-auth/register' , 'CustomAuth\RegisterController@index')->name('custom-auth/register');
Route::post('custom-auth/register' , 'CustomAuth\RegisterController@register');

Route::get('/pages/dataTable',function(){ return view('pages.dataTable');});


Route::resource('contacts' , 'ContactController');
Route::resource('catagories' , 'CatagoryController');

resources/views/CustomHome.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <script src="{{ asset('js/jquery.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('js/additional-methods.min.js') }} "></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div class="container">
    @if(Route::has('custom-auth/login'))
    <div class="top-right links">
        @if(Auth::check())
            <a href="{{ url('/') }}">Home</a>
        <a href="{{ url('custom-auth/logout') }}">Logout
     </a>
       
        @else
            <a href="{{ route('custom-auth/login') }}">Login</a>

            <a href="{{ route('custom-auth/register') }}">Register</a>
        @endif
    </div>
    @endif
    <div class="row">
        <div class="col-sm-12">
            @if(session('success'))
                <div class="alert" role="alert">
                    {{session('success')}}
                </div>
            @endif
        <h1 class="text-primary">Name is {{Auth::user()->name}}</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
        <h1 class="text-primary">Email is {{Auth::user()->email}}</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
        <a href="CustomHome" class="btn btn-primary">View Profile</a>
        <a href="edit-profile/{{Auth::user()->id}}" class="btn btn-success">Update Profile</a>
        </div>
    </div>
</div>

</body>
</html>

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Laravel 7 & MySQL CRUD Tutorial</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    
  <script src="{{ asset('js/app.js') }}" ></script>

  
</head>
<body>
  <div class="container">
    @include('sweet::alert')
    @yield('main')
  </div>
</body>
</html>

resources/views/catagoryBase.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Catagory</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    
  <script src="{{ asset('js/app.js') }}" ></script>

  
</head>
<body>
  <div class="container">
    @include('sweet::alert')
    @yield('main')
  </div>
</body>
</html>

resources/views/custom.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="{{ asset('js/app.js') }}"></script>
        
        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if(Route::has('custom-auth/login'))
                <div class="top-right links">
                    @if(Auth::check())
                        <a href="{{ url('/') }}">Home</a>
                        <a href="{{ url('/CustomHome') }}">Dashboard</a>
                    </a>
                    <a href="{{ url('custom-auth/logout') }}">Logout</a>
                   
                    @else
                        <a href="{{ route('custom-auth/login') }}">Login</a>

                        <a href="{{ route('custom-auth/register') }}">Register</a>
                    @endif
                </div>
            @endif
            
            <div class="content">
                <div class="title m-b-md">
                    Laravel
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Docs</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://blog.laravel.com">Blog</a>
                    <a href="https://nova.laravel.com">Nova</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://vapor.laravel.com">Vapor</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                        <div class="panel-body">
                            <a href="{{ route('catagories.create') }}" class="btn btn-primary">Create Ctagory</a>
                            <h3>Your Catagories</h3>
                            @if(count($catagories) > 0)
                            <table class="table table-striped">
                                <tr>
                                    <th>Nmae</th>
                                    <th colspan="2">Acions</th>
                                </tr>
                                @foreach($catagories as $userCatagory)
                                <tr>
                                    <th>{{ $userCatagory->name }}</th>
                                    <th><a href="{{ url('catagories/'.$userCatagory->user_id.'/edit') }}" class="btn btn-primary">Edit</a></th>
                                    <th><a href="#" class="btn btn-danger">Delete</a></th>
                                </tr>
                                @endforeach
                            </table>
                            @else
                            <p>you have no catagories yet</p>
                            @endif
                        </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection