routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); });

//Route::get('/', function () { return view('custom'); });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/mypage','pageController@index');
Route::get('/view-profile', 'HomeController@viewProfile');
Route::get('{id}/edit', 'HomeController@edit');
Route::post('/update-profile', 'HomeController@updateProfile');

Route::get('/pages/pushstack', function() { return view('pages.pushstack'); });

//Custom Password reset routes
/*Route::get('/password/confirm' , 'CustomAuth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('/password/confirm' , 'CustomAuth\ConfirmPasswordController@confirm');
Route::post('/password/email' , 'CustomAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('custom-auth/password/reset' , 'CustomAuth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('custom-auth/password/reset' , 'CustomAuth\ResetPasswordController@reset')->name('password.update');
Route::get('/password/reset/{token?}' , 'CustomAuth\ResetPasswordController@showResetForm')->name('password.reset');*/


Route::get('/custom-auth/login' , 'CustomAuth\LoginController@index')->name('custom-auth/login');
Route::post('/custom-auth/login' , 'CustomAuth\LoginController@login');
Route::get('/custom-auth/logout' , 'CustomAuth\LoginController@logout');
Route::get('/custom-auth/forgot-password' , 'CustomAuth\ForgotPasswordController@index');

Route::get('/CustomHome' , 'CustomHomeController@index');
Route::get('/edit-profile/{id}' , 'CustomAuth\EditProfileController@index');
Route::post('/edit-profile/{id}' , 'CustomAuth\EditProfileController@updateProfile');

Route::get('/custom-auth/register' , 'CustomAuth\RegisterController@index')->name('custom-auth/register');
Route::post('custom-auth/register' , 'CustomAuth\RegisterController@register');

Route::get('/pages/dataTable',function(){ return view('pages.dataTable');});


Route::resource('contacts' , 'ContactController');
Route::resource('catagories' , 'CatagoryController');

app/Catagory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\user;
class Catagory extends Model
{
    public $timestamps = false;
    protected $table= 'catagories';
    protected $fillable = ['user_id','name'];
    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/CatagoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Catagory;
use DB;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Support\Facades\Auth;
class CatagoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $catagoryUser = Catagory::all();
        return view('catagories.index' , compact('catagoryUser'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('catagories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request ,[
           'name' => 'required|min:2'
       ]);
        $user_id = auth()->user()->id;
        $catagory = new Catagory;
        $catagory->user_id = $user_id;
        $catagory->name = $request->get('name');
        $catagory->save();
        return redirect('/catagories')->with('success' , 'catagory has been saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
        $id = $request->user()->id;
        $catagoryUser = DB::table('catagories')->where('user_id', $id)->first();;
        return view('catagories.edit')->with('catagory' , $catagoryUser);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request ,[
            'name' => 'required|min:2'
        ]);
         $catagory = DB::table('catagories')->where('user_id', $id)->update(['name' => $request->get('name')]);
         return redirect('catagories')->with('success' , 'catagory has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/catagories/create.blade.php
@extends('catagoryBase')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create Catagory</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      
    {!!Form::open(['route' => 'catagories.store' , 'method' => 'post'])!!}
    {{Form::token()}}
  <div class="form-group">
        {{Form::label('name' , 'Enter Catagory Name:')}}
        {{Form::text('name' , null , ['class' =>'form-control' , 'id' => 'name' , 'minlength' => 2 , 'maxlength' => 20])}}
    </div>

    <div class="form-group">
        {{Form::submit('Add Catagory' , ['class' =>'btn btn-primary'])}}
    </div>
    {!!Form::close()!!}

  </div>
</div>
</div>
@endsection

resources/views/catagories/edit.blade.php
@extends('catagoryBase')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Catagory</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      
    {!!Form::open(['route' => ['catagories.update' , $catagory->name] , 'method' => 'PATCH'])!!}
    {{Form::token()}}
  <div class="form-group">
        {{Form::label('name' , 'Enter Catagory Name:')}}
        {{Form::text('name' , $catagory->name , ['class' =>'form-control'  , 'minlength' => 2 , 'maxlength' => 20])}}
    </div>

    <div class="form-group">
        {{Form::submit('Update Catagory' , ['class' =>'btn btn-primary'])}}
    </div>
    {!!Form::close()!!}

  </div>
</div>
</div>
@endsection

resources/views/catagories/index.blade.php
@extends('catagoryBase')
@section('main')

<div class="col-sm-12">

    @if(session()->get('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}  
      </div>
    @endif

    @if(session()->get('error'))
    <div class="alert alert-danger">
      {{ session()->get('error') }}  
    </div>
    @endif
    
 
    
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Catagories</h1> 
    <div>
        <a style="margin: 19px;" href="{{ route('catagories.create')}}" class="btn btn-primary">New catagory</a>
    </div>

    {{ Breadcrumbs::render('catagory') }}

  <table id="myTable" class="display">
    <thead>
        <tr>
          <td>User Id</td>
          <td>Name</td>
        </tr>
    </thead>
    <tbody>
      @foreach($catagoryUser as $user)
      <tr>
          <td>{{$user->user_id}}</td>
          <td>{{$user->name}}</td>
          <td>
              <a href="{{ route('catagories.edit',$user->user_id)}}" class="btn btn-primary btn-sm">Edit</a>

            <button class="btn btn-danger btn-sm">Delete</button> 
            <!--<form action="{{ route('catagories.destroy',$user->user_id)}}" method="post">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger" type="submit">Delete</button>
              </form>-->
          </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <script>
    $(document).ready( function () {
     $('#myTable').DataTable();
 });
</script>
@endsection