routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('welcome'); });

//Route::get('/', function () { return view('custom'); });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/mypage','pageController@index');
Route::get('/view-profile', 'HomeController@viewProfile');
Route::get('{id}/edit', 'HomeController@edit');
Route::post('/update-profile', 'HomeController@updateProfile');

Route::get('/pages/pushstack', function() { return view('pages.pushstack'); });

//Custom Password reset routes
/*Route::get('/password/confirm' , 'CustomAuth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('/password/confirm' , 'CustomAuth\ConfirmPasswordController@confirm');
Route::post('/password/email' , 'CustomAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('custom-auth/password/reset' , 'CustomAuth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('custom-auth/password/reset' , 'CustomAuth\ResetPasswordController@reset')->name('password.update');
Route::get('/password/reset/{token?}' , 'CustomAuth\ResetPasswordController@showResetForm')->name('password.reset');*/


Route::get('/custom-auth/login' , 'CustomAuth\LoginController@index')->name('custom-auth/login');
Route::post('/custom-auth/login' , 'CustomAuth\LoginController@login');
Route::get('/custom-auth/logout' , 'CustomAuth\LoginController@logout');
Route::get('/custom-auth/forgot-password' , 'CustomAuth\ForgotPasswordController@index');

Route::get('/CustomHome' , 'CustomHomeController@index');
Route::get('/edit-profile/{id}' , 'CustomAuth\EditProfileController@index');
Route::post('/edit-profile/{id}' , 'CustomAuth\EditProfileController@updateProfile');

Route::get('/custom-auth/register' , 'CustomAuth\RegisterController@index')->name('custom-auth/register');
Route::post('custom-auth/register' , 'CustomAuth\RegisterController@register');

Route::get('/pages/dataTable',function(){ return view('pages.dataTable');});


Route::resource('contacts' , 'ContactController');
Route::resource('catagories' , 'CatagoryController');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'city',
        'country',
        'job_title'
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ContactsForm;
use App\Contact;
use Validator;
use UxWeb\SweetAlert\SweetAlert;
use Illuminate\Validation\Rule;
class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $contacts = Contact::all();
       return view('contacts.index' , compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContactsForm $request)
    {
     
        /*   
        $request->validated();
            
        $request->validate([
            'first_name' => 'required|min:2',
            'last_name' => 'required|min:2',
            'email' => 'required|email|unique:contacts',
            'job_title' => 'required' ,
            'city' => 'required',
            'country' => 'required'
        ]);
        $validator = validator::make($request->all() , [
            'first_name' => 'required|min:2',
            'last_name' => 'required|min:2',
            'email' => 'required|email',
            'job_title' => 'required' ,
            'city' => 'required',
            'country' => 'required'
        ])->validate();

        Validator::make($request->all(), [
            'email' => [
                'required',
                Rule::unique('contacts'),
            ],
        ])->validate();*/

        $contact = new Contact([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'email' => $request->get('email'),
            'job_title' => $request->get('job_title'),
            'city' => $request->get('city'),
            'country' => $request->get('country')
        ]);
        $contact->save();
        return redirect('/contacts')->with('success' , 'contact saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = Contact::find($id);
        return view('contacts.edit' , compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'first_name' => 'required|min:2',
            'last_name' => 'required|min:2',
            'email' => 'required|email',
            'job_title' => 'required' ,
            'city' => 'required',
            'country' => 'required'
        ]);

        $contact = Contact::find($id);
        $contact->first_name =  $request->get('first_name');
        $contact->last_name = $request->get('last_name');
        $contact->email = $request->get('email');
        $contact->job_title = $request->get('job_title');
        $contact->city = $request->get('city');
        $contact->country = $request->get('country');
        $contact->save();
            alert()->success('Contact have been updated successfully','Contact Updated');
        return redirect('/contacts')->with('success', 'Contact updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();

        return redirect('/contacts')->with('success', 'Contact deleted!');
    }
}

resources/views/contacts/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a contact</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      
    {!!Form::open(['route' => 'contacts.store' , 'method' => 'post' , 'id' => 'contactCreateForm'])!!}
    {{Form::token()}}
    <div class="form-group">
        {{Form::label('first_name' , 'First Name:')}}
        {{Form::text('first_name' , null , ['class' =>'form-control' , 'id' => 'first_name' , 'minlength' => 2 , 'maxlength' => 20])}}
    </div>

    <div class="form-group">
        {{Form::label('last_name' , 'Last Name:')}}
        {{Form::text('last_name' , null , ['class' =>'form-control' , 'id' => 'last_name' , 'minlength' => 2 , 'maxlength' => 20 ])}}
    </div>

    <div class="form-group">
        {{Form::label('email' , 'Email:')}}
        {{Form::email('email' , null , ['class' =>'form-control' , 'id' => 'email' , 'email' => 'true'])}}
    </div>

    <div class="form-group">
        {{Form::label('city' , 'City:')}}
        {{Form::text('city' , null , ['class' =>'form-control' , 'id' => 'city'])}}
    </div>

    <div class="form-group">
        {{Form::label('country' , 'Country:')}}
        {{Form::text('country' , null , ['class' =>'form-control' , 'id' => 'country'])}}
    </div>

    <div class="form-group">
        {{Form::label('job_title' , 'Job Title:')}}
        {{Form::text('job_title' , null , ['class' =>'form-control' , 'id' => 'job_title'])}}
    </div>

    <div class="form-group">
        {{Form::submit('Add Contact' , ['class' =>'btn btn-primary'])}}
    </div>
    {!!Form::close()!!}

  </div>
</div>
</div>
@endsection

resources/views/contacts/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a contact</h1>
        
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        
        {{ Breadcrumbs::render('edit') }}

        {!!Form::open(['route' => ['contacts.update' , $contact->id ] , 'method' => 'PATCH'])!!}
        {{Form::token()}}
        <div class="form-group">
            {{Form::label('first_name' , 'First Name:')}}
            {{Form::text('first_name' , $contact->first_name , ['class' =>'form-control' , 'id' => 'first_name' , 'minlength' => 2 , 'maxlength' => 20 , 'required' => 'true'])}}
        </div>
    
        <div class="form-group">
            {{Form::label('last_name' , 'Last Name:')}}
            {{Form::text('last_name' , $contact->last_name , ['class' =>'form-control' , 'id' => 'last_name' , 'minlength' => 2 , 'maxlength' => 20 , 'required' => 'true'])}}
        </div>
    
        <div class="form-group">
            {{Form::label('email' , 'Email:')}}
            {{Form::email('email' , $contact->email , ['class' =>'form-control' , 'id' => 'email' , 'email' => 'true' , 'required' => 'true'])}}
        </div>
    
        <div class="form-group">
            {{Form::label('city' , 'City:')}}
            {{Form::text('city' , $contact->city , ['class' =>'form-control' , 'id' => 'city' , 'required' => 'true'])}}
        </div>
    
        <div class="form-group">
            {{Form::label('country' , 'Country:')}}
            {{Form::text('country' , $contact->country , ['class' =>'form-control' , 'id' => 'country' , 'required' => 'true'])}}
        </div>
    
        <div class="form-group">
            {{Form::label('job_title' , 'Job Title:')}}
            {{Form::text('job_title' , $contact->job_title , ['class' =>'form-control' , 'id' => 'job_title'])}}
        </div>
    
        <div class="form-group">
            {{Form::submit('Update' , ['class' =>'btn btn-primary'])}}
        </div>
        {!!Form::close()!!}
        
    </div>
</div>
@endsection

resources/views/contacts/index.blade.php
@extends('base')

@section('main')
<div class="col-sm-12">

    @if(session()->get('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}  
      </div>
    @endif
  </div>
    
 
    
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Contacts</h1> 
    <div>
        <a style="margin: 19px;" href="{{ route('contacts.create')}}" class="btn btn-primary">New contact</a>
    </div>

    {{ Breadcrumbs::render('contacts') }}

  <table id="myTable" class="display">
    <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Email</td>
          <td>Job Title</td>
          <td>City</td>
          <td>Country</td>
          <td>Actions</td>
        </tr>
    </thead>
    <tbody>
      @foreach($contacts as $contact)
      <tr>
          <td>{{$contact->id}}</td>
          <td>{{$contact->first_name}} {{$contact->last_name}}</td>
          <td>{{$contact->email}}</td>
          <td>{{$contact->job_title}}</td>
          <td>{{$contact->city}}</td>
          <td>{{$contact->country}}</td>
          <td>
              <a href="{{ route('contacts.edit',$contact->id)}}" class="btn btn-primary btn-sm">Edit</a>

            <button onclick="deleteData({{$contact->id}})" class="btn btn-danger btn-sm">Delete</button> 
            <!--<form action="{{ route('contacts.destroy', $contact->id)}}" method="post">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger" type="submit">Delete</button>
              </form>-->
          </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <script>
        $(document).ready( function () {
        var table = $('#myTable').DataTable();
      });
    </script>
    <script>

 function deleteData(id) {
  var csrf_token = $('meta[name="csrf-token"]').attr('content');
 swal({
   title : "are you sure?" , 
   text : "once deleted , you will not be able to recover data again?",
   icon : "warning",
   buttons : true,
   dangerMode: true,
 }).then((willDelete) => {
   if(willDelete) {
     $.ajax({
       url : "{{ url('contacts')}}" + '/' + id,
       type : "POST",
       data : {'_method' : 'DELETE', '_token' : csrf_token},
       success : function(data) {
        table.ajax.reload();
         swal({
           title : "delete done",
           text : "you clicked the button",
           icon : "success",
           button :"done"
         })
       },
       error : function() {
         swal({
           title : 'opps',
           text : 'something happened wrong',
           type : 'error',
           timer : '1500'
         })
       }
     });
   } else {
     swal('your file is safe!');
   }
 });
} 
</script>

@endsection